version: '3'
services:
  aws:
    image: amazon/aws-cli
    volumes:
      - .:/app/terraform
    env_file: .env
  terraform:
    image: hashicorp/terraform:1.1.0
    volumes:
      - .:/app/terraform
    env_file: .env
    working_dir: /app/terraform
